(#254) codegen: if else block
dannypsnl/elz pull request #256
Opened 2020-02-20 13:11 UTC by dannypsnl

resolve #254

2020-02-20 13:31 UTC, dannypsnl commented
@YanHerChen To review this PR, [elz wiki](https://github.com/dannypsnl/elz/wiki/LLVM-Notes) might help. The point is to ensure this PR work correctly and readable enough for you. The unit test could help you get the target of the code generator.

NOTE:
- `Rc` is a single-thread reference-counting pointer in Rust
- ir means: [Intermediate representation](https://en.wikipedia.org/wiki/Intermediate_representation)
- In ir, there only has no nested block
- **continues terminators** this situation is invalid in LLVM

2020-02-21 06:11 UTC, dannypsnl commented on src/codegen/ir.rs
> +/// LLVM example: `; <label>:9:`, here `id` is `9`
NOTE: Remove outdated comment

2020-02-21 06:11 UTC, dannypsnl commented on src/codegen/ir.rs
> -    pub(crate) statements: Vec<Instruction>,
Reverse instructions and counter to remove this comment

2020-02-21 06:11 UTC, dannypsnl commented on src/codegen/ir.rs
> +                body.instructions = vec![Instruction::Return(Some(Expr::from_ast(e, module)))];
instructions.push?

2020-02-21 06:11 UTC, dannypsnl commented on src/codegen/ir.rs
> +                    self.instructions.push(inst)
Remove temp variable: inst?

2020-02-21 06:11 UTC, dannypsnl commented on src/codegen/ir.rs
> +        if let Some(inst) = self.instructions.last() {
Maybe we should judge duplicate terminator case by case?

2020-02-21 06:11 UTC, dannypsnl commented on src/codegen/llvm.rs
> +    }
Probably introduce a label.name() to keep ”label<id>” consistently?

2020-02-21 09:22 UTC, YanHerChen requested changes

2020-02-21 09:22 UTC, YanHerChen commented on src/codegen/llvm.rs
> +                ir::Instruction::Label(_) => {
probably replace _ with ..

2020-02-23 15:31 UTC, dannypsnl commented
@YanHerChen PR updated! Please review again.

2020-02-23 15:36 UTC, YanHerChen approved these changes

2020-02-23 16:02 UTC, merged