(#271) fix bug: missing to check class field
dannypsnl/elz pull request #272
Opened 2020-03-02 13:23 UTC by dannypsnl

2020-03-02 13:35 UTC, dannypsnl commented on src/codegen/mod.rs
> +                                );
@YanHerChen Here transform object-orient to pure procedure-orient code. Since IR don't support concept **class**

2020-03-02 13:35 UTC, dannypsnl commented on src/parser/mod.rs
> -                    );
Originally, we do transform at parser. Now I remove it.

2020-03-02 13:35 UTC, dannypsnl commented on src/parser/tests.rs
> -                    ],
related to transforming, so removed.

2020-03-02 13:35 UTC, dannypsnl commented on src/semantic/error.rs
> +    #[error("redefined field `{}` in class `{}`, already defined at {}", .field_name, .class_name, .previous_definition)]
@YanHerChen Seems like I forget to change naming, it should be `member`, not `field`. Please do request changes here

2020-03-02 13:35 UTC, dannypsnl commented on src/semantic/mod.rs
> +                    }
Here the target is to make sure each type already been emitted before others type uses it. But seems like 40 to 43 is useless code.

2020-03-02 13:35 UTC, dannypsnl commented on src/semantic/types.rs
> +
Here are new structures to control the class member concept in the type checker.

2020-03-02 13:37 UTC, dannypsnl commented on src/semantic/mod.rs
> +                    }
I already remove the unused code but leave the comment for your review.

2020-03-03 09:20 UTC, YanHerChen approved these changes

2020-03-03 09:20 UTC, YanHerChen commented on src/semantic/error.rs
> +    #[error("redefined field `{}` in class `{}`, already defined at {}", .field_name, .class_name, .previous_definition)]
please use `member`, instead of `field`.

2020-03-03 09:22 UTC, YanHerChen requested changes

2020-03-03 09:22 UTC, YanHerChen commented on src/semantic/error.rs
> +    #[error("redefined field `{}` in class `{}`, already defined at {}", .field_name, .class_name, .previous_definition)]
please use `member`, instead of `field`.

2020-03-04 02:40 UTC, merged