(#301) fix module statement format
dannypsnl/elz pull request #303
Opened 2020-04-07 13:14 UTC by YanHerChen

2020-04-07 13:27 UTC, dannypsnl requested changes

2020-04-07 13:27 UTC, dannypsnl commented on src/codegen/formatter/tests.rs
> +module main
there will not have two module declarations. Therefore, the test seems nonsense.

2020-04-14 06:26 UTC, dannypsnl commented on src/codegen/formatter/tests.rs
> +module main
```suggestion
        "module str
```

2020-04-18 06:02 UTC, YanHerChen commented on src/codegen/formatter/tests.rs
> +module main
fix problem already

2020-04-18 06:10 UTC, dannypsnl approved these changes

2020-04-18 06:10 UTC, merged